[project]
name = "qdrant-bge-m3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastembed>=0.7.1",
    "flagembedding>=1.3.5",
    "qdrant-client>=1.14.3",
    "sentence-transformers>=4.1.0",
]
